name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start minikube
      uses: medyagh/setup-minikube@master
      with:
        minikube-version: 'latest'
        kubernetes-version: 'v1.28.0' # Keep this for consistency

    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Build image
      run: |
          eval $(minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images

    - name: Deploy to minikube
      run: |
        kubectl apply -f k8-node.app.yaml

    - name: Wait for Deployment Rollout (Crucial for pod readiness and to see crashes)
      run: |
        echo "Waiting for deployment to rollout (up to 3 minutes)."
        # Use a longer timeout and allow failure so subsequent debug steps run
        kubectl rollout status deployment/nodejs-app-deployment --timeout=3m || true
        echo "Deployment rollout status check complete."

    - name: Get detailed Pod Status and Events (Enhanced Debugging)
      run: |
        echo "--- Listing all pods in default namespace (wide view): ---"
        kubectl get pods -n default -o wide

        echo "--- Getting pod name for nodejs-app: ---"
        # Safely get the pod name, handling cases where it might not be immediately available
        POD_NAME=$(kubectl get pods -n default -l app=nodejs-app -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")

        if [ -n "$POD_NAME" ]; then
          echo "--- Describing pod: $POD_NAME ---"
          kubectl describe pod "$POD_NAME" -n default

          echo "--- Attempting to fetch logs for pod: $POD_NAME ---"
          # Try to get current logs, then previous logs if it restarted
          kubectl logs "$POD_NAME" -n default --since=1m || kubectl logs "$POD_NAME" -n default --previous || echo "  >> Could not get current or previous logs (container might not be running or just started)."

          echo "--- Getting detailed YAML for pod: $POD_NAME (shows exit codes/last state) ---"
          kubectl get pod "$POD_NAME" -n default -o yaml

          echo "--- Getting events specifically for pod: $POD_NAME ---"
          kubectl get events -n default --field-selector involvedObject.name="$POD_NAME"
        else
          echo "  >> No 'nodejs-app' pod found by label 'app=nodejs-app' after rollout attempt."
          echo "--- Listing all events in default namespace (to see any issues that prevented pod creation): ---"
          kubectl get events -n default
        fi
      # Continue on error for this debug step so the next steps still run
      continue-on-error: true

    - name: Test service URLs
      run: |
          minikube service list
          minikube service nodejs-app --url
